version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: rinha-db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432